# Generated by Django 5.2.1 on 2025-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='natomember',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
